FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py db.py models.py dependencies.py schemas.py ./
COPY routers ./routers
COPY alembic ./alembic
COPY alembic.ini .

ENV DATABASE_URL=postgresql://postgres:postgres@db:5432/fitness

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
